apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/template
            pathType: Prefix
            backend:
              service:
                name: template-clusterip-srv
                port:
                  number: 8080
          - path: /java-1
            pathType: Prefix
            backend:
              service:
                name: java-1-clusterip-srv
                port:
                  number: 8080